In [1]:
import pandas as pd

In [3]:

df_train = pd.read_feather("../data/merge/train_merge.feather")

In [5]:

df_train["TransactionDay"] = df_train["TransactionDT"] / 60 / 24 // 24

In [6]:
df_train["TransactionDay"]

0           2.0
1           2.0
2           2.0
3           2.0
4           2.0
          ...
590535    457.0
590536    457.0
590537    457.0
590538    457.0
590539    457.0
Name: TransactionDay, Length: 590540, dtype: float64

In [7]:
[x for x in df_train.columns if "D" in x]

['TransactionID',
 'TransactionDT',
 'ProductCD',
 'DeviceType',
 'DeviceInfo',
 'D11_mod7',
 'D3_mod7',
 'D2_mod7',
 'D4_mod7',
 'D8_mod7',
 'D10_mod7',
 'D9_mod7',
 'D_mod7_pca0',
 'D_mod7_pca1',
 'D_mod7_pca2',
 'D_mod7_pca3',
 'D_mod7_pca4',
 'D_mod7_svd0',
 'D_mod7_svd1',
 'D_mod7_svd2',
 'D_mod7_svd3',
 'D_mod7_svd4',
 'D15_mod7',
 'D12_mod7',
 'D_isnan_sum',
 'D_iszero_sum',
 'D5-6-7-8_nancount',
 'D5-6-7-8_zerocount',
 'D12-13-14_nancount',
 'D12-13-14_zerocount',
 'D13_mod7',
 'D6_mod7',
 'D5_mod7',
 'D14_mod7',
 'D7_mod7',
 'D1_mod7',
 'TransactionDay_normalize',
 'TransactionDT_isDecember',
 'TransactionDT_month_in_quarter',
 'TransactionDT_month_in_half-yearly',
 'TransactionDT_hhmmss',
 'diff_TransactionDay_D1',
 'diff_TransactionDay_D2',
 'diff_TransactionDay_D3',
 'diff_TransactionDay_D4',
 'diff_TransactionDay_D5',
 'diff_TransactionDay_D6',
 'diff_TransactionDay_D7',
 'diff_TransactionDay_D8',
 'diff_TransactionDay_D9',
 'diff_TransactionDay_D10',
 'diff_TransactionDay_D11',
 'diff_TransactionDay_D12',
 'diff_TransactionDay_D13',
 'diff_TransactionDay_D14',
 'diff_TransactionDay_D15',
 'TransactionDay_ProductCD_countencoding',
 'TransactionWeek_ProductCD_countencoding',
 'TransactionQuarter_ProductCD_countencoding',
 'TransactionHalfyearly_ProductCD_countencoding',
 'TransactionDecember_ProductCD_countencoding',
 'countencoding_D8',
 'countencoding_D3',
 'countencoding_D10',
 'countencoding_D6',
 'countencoding_D14',
 'countencoding_D1',
 'countencoding_D13',
 'countencoding_D5',
 'countencoding_D7',
 'countencoding_D9',
 'countencoding_D12',
 'countencoding_DeviceType',
 'countencoding_D11',
 'countencoding_D2',
 'countencoding_D15',
 'countencoding_D4',
 'countencoding_DeviceInfo',
 'countencoding_ProductCD',
 'agg_D1divcard2mean',
 'agg_D2divid_32mean',
 'agg_D2divcard1mean',
 'agg_D2divid_37mean',
 'agg_D1divid_25mean',
 'agg_V244divProductCDmean',
 'agg_D15divcard6mean',
 'agg_D4divcard3mean',
 'agg_D15divid_14mean',
 'agg_D15divcard1mean',
 'agg_D10divid_23mean',
 'agg_D15divid_31mean',
 'agg_D2divid_25mean',
 'agg_D2divid_38mean',
 'agg_D2divid_28mean',
 'agg_D15divM4mean',
 'agg_D15divcard3mean',
 'agg_D2divcard2mean',
 'agg_D10divcard4mean',
 'agg_D2divM5mean',
 'agg_D2divM9mean',
 'agg_D1divid_16mean',
 'agg_D4divid_23mean',
 'agg_D15divid_23mean',
 'agg_D2divcard3mean',
 'agg_D2divid_23mean',
 'agg_D15divM8mean',
 'agg_D2divcard5mean',
 'agg_D2divid_35mean',
 'agg_D2divid_15mean',
 'agg_D15divcard5mean',
 'agg_D2divid_22mean',
 'agg_D15divid_17mean',
 'agg_TransactionAmtdivProductCDmean',
 'agg_D2divid_27mean',
 'agg_D4divid_25mean',
 'agg_D15divcard4mean',
 'agg_D2divcard6mean',
 'agg_D15divid_35mean',
 'agg_C13divProductCDmean',
 'agg_D1divid_26mean',
 'TransactionDay']

In [9]:
aaa = df_train.groupby(["card1", "card2", "card3", "diff_TransactionDay_D15"]).agg({"isFraud": ["mean", "count"]})

In [11]:
aaa.columns = ["mean", "count"]

In [13]:
aaa = aaa.sort_values("count", ascending=False)

In [14]:
aaa

                                               mean  count
card1 card2 card3 diff_TransactionDay_D15
9500  321.0 150.0  299.0                   0.000000    356
7919  194.0 150.0 -92.0                    0.000000    291
                  -63.0                    0.018116    276
                  -64.0                    0.026786    224
8900  385.0 150.0  168.0                   0.000000    217
...                                             ...    ...
8718  321.0 150.0 -162.0                   0.000000      1
8717  489.0 150.0  343.0                   0.000000      1
                  -21.0                    0.000000      1
                  -36.0                    0.000000      1
18395 543.0 150.0 -17.0                    0.000000      1

[146734 rows x 2 columns]

In [19]:
df_train.query("card1=='9500' and card2=='321' and card3=='150' and diff_TransactionDay_D15=='299'").to_csv("test.csv")

df_train.query("card1=='7919' and card2=='194' and card3=='150' and diff_TransactionDay_D15==-92").to_csv("test2.csv")

In [18]:
df_test = pd.read_feather("../data/merge/test_merge.feather")

In [20]:
df_train.query("diff_TransactionDay_D15 < 0")["isFraud"].mean()

0.045650175267663205

In [23]:
aaa.reset_index().query("diff_TransactionDay_D15>=0 and count>40")

     card1  card2  card3  diff_TransactionDay_D15  mean  count
0     9500  321.0  150.0                    299.0   0.0    356
4     8900  385.0  150.0                    168.0   0.0    217
6     7207  111.0  150.0                    475.0   0.0    208
8     8528  215.0  150.0                    159.0   0.0    184
11   15775  481.0  150.0                     85.0   0.0    172
..     ...    ...    ...                      ...   ...    ...
500  15986  360.0  150.0                    467.0   0.0     41
508  12544  321.0  150.0                     54.0   0.0     41
510   3682  264.0  150.0                    136.0   0.0     41
512   7508  321.0  150.0                    481.0   0.0     41
513  17188  321.0  150.0                    474.0   0.0     41

[205 rows x 6 columns]

In [27]:
bbb =  df_train.groupby(["card1", "card2", "card3", "diff_TransactionDay_D1"]).agg({"isFraud": ["mean", "count"]})
bbb.columns = ["mean", "count"]

In [28]:
bbb.sort_values("count", ascending=False)

                                              mean  count
card1 card2 card3 diff_TransactionDay_D1
15775 481.0 150.0 -129.0                  0.000000   1414
9500  321.0 150.0  85.0                   0.000000    480
7919  194.0 150.0 -92.0                   0.000000    439
                  -1.0                    0.004878    410
                  -34.0                   0.003003    333
...                                            ...    ...
8830  250.0 150.0 -98.0                   0.000000      1
                  -121.0                  0.000000      1
                  -126.0                  0.000000      1
                  -138.0                  0.000000      1
18396 111.0 150.0 -25.0                   0.000000      1

[148049 rows x 2 columns]

In [29]:
df_train.query("card1=='15775' and card2=='481' and card3=='150' and diff_TransactionDay_D1==-129").to_csv("test.csv")

In [30]:
df_test = pd.read_feather("../data/original/test_all.feather")

In [31]:
df_test.head(1000).to_csv("test_all_head1000.csv", index=False)